Monday-09-25
illuminate3/minuet pull request #103
Opened 2023-09-25 09:25 UTC by miteshqodic

Monday-09-25

2023-09-25 23:47 UTC, illuminate3 requested changes
I don't see why we keep the files with the word Buyer in them.
I do know why it would be an easy choice to do that.

Should we add Buyer to all files?

The decision should be made as to which one would provide cleaner and easier to understand code.

I spend hours cleaning up and reorganizing code. I don't want to keep doing that. Let's please try to clean up the code.

2023-09-25 23:47 UTC, illuminate3 commented on src/Message/SendEmailConfirmationAndResetPassword.php
Why was this file deleted and not the one with the word Buyer in it?

2023-09-25 23:47 UTC, illuminate3 commented on src/MessageHandler/SendEmailConfirmationAndResetPasswordLinkHandler.php
Why was this file deleted and not the one with the word Buyer in it?

2023-09-25 23:47 UTC, illuminate3 commented on src/Service/Auth/EmailVerifierAndResetPasswordService.php
Why was this file deleted and not the one with the word Buyer in it?

2023-09-26 05:25 UTC, miteshqodic commented
> I don't see why we keep the files with the word Buyer in them. I do know why it would be an easy choice to do that.
> 
> Should we add Buyer to all files?
> 
> The decision should be made as to which one would provide cleaner and easier to understand code.
> 
> I spend hours cleaning up and reorganizing code. I don't want to keep doing that. Let's please try to clean up the code.

Initially, we have the filename without the buyer word, then we combined dealer and buyer code.
then we decided to change the flow and buyer and dealer should be separate project, so files exists since that time.

Ok no worries, I will remove buyer word files and user without that and make appropriate changes and push

2023-09-26 23:48 UTC, illuminate3 approved these changes

2023-09-26 23:50 UTC, merged