MN-8-left-column-sorting
illuminate3/minuet pull request #13
Opened 2023-05-11 12:55 UTC by Devscaleupally

Showing all products by default
Showing all categories(make)
Showing all sub categories(models) after the selection of category(make)
Showing filtered products after the selection of model.
Show no-products-found image if product are empty in list.
Fix side space bug because of the extra footer(footer inside footer)
Fix spacing issue in products listing page in mobile screen
Show filters with mobile responsiveness
UI of Models

2023-05-12 02:11 UTC, illuminate3 requested changes
Please always pull from main before doing a commit.
I have added my comments.

2023-05-12 02:11 UTC, illuminate3 commented on src/Controller/ProductController.php
I don't think we need the commented out code anymore, so you can delete.

It's not really good code practice to inline SQL queries in a controller. Please move those to a method in ProuductRepository.

Please don't put the API call in this controller. APIs also need to be versioned and stateless. Updates will happen and developers don't look for the API here.

2023-05-12 02:11 UTC, illuminate3 commented on public/us-car-models-data-master/1992.csv
Did you pull from master before doing this commit? Normally, all the files in master wouldn't show up here.

2023-05-12 02:11 UTC, illuminate3 commented on config/routes.yaml
This route most likely could be annotated in the controller.

2023-05-12 02:11 UTC, illuminate3 commented on templates/product/index.html.twig
If the url removes the parameter then the nested Laravel style of blade conditional will need to changed.

Please move the javascript to it's own file, load it webpack, and then call the webpack asset.

2023-05-13 00:00 UTC, illuminate3 requested changes
Getting better.
Please follow Symfony best and standard practices.

2023-05-15 08:28 UTC, Devscaleupally commented on public/assets/css/style.css
okay @illuminate3

2023-05-15 08:32 UTC, Devscaleupally commented on templates/product/index.html.twig
>  $(function() {
Okay sure. I will create a javascript file and  load it through webpack.

2023-05-15 08:40 UTC, Devscaleupally commented on src/Controller/ProductController.php
> +    #[Route(path: '/', name: 'product_index', defaults: ['page' => 1], methods: ['GET','POST'])]
Sure, I understand now. You want to use a clean URL structure like "product/makeId/modelId" instead of passing the parameters in the URL like "product?makeId=123&modelId=456". I was using the post method to hide the params from url.

2023-05-15 08:41 UTC, Devscaleupally commented on public/assets/css/style.css
>      padding: 6px 12px;
okay sure. I will remove my custom classes.

2023-05-15 08:44 UTC, Devscaleupally commented on public/us-car-models-data-master/1992.csv
Yes last time I took the pull. I will again take the pull and push the code with fix conflicts

2023-05-15 09:22 UTC, Devscaleupally commented on config/routes.yaml
Actually mostly I do routing in routes.yaml.  So I created the route here. No this route is no more needed so I will remove it from here. We can directly fetch the models at the time of make filter.

2023-05-16 00:52 UTC, illuminate3 commented on public/assets/css/style.css
54 files are showing.
You did do pull from main.
Hmmm, did you merge or just pull?

2023-05-16 00:52 UTC, illuminate3 commented on public/us-car-models-data-master/1992.csv
54 files are showing.
You did do pull from main.
Hmmm, did you merge or just pull?

2023-05-16 01:00 UTC, illuminate3 commented on public/assets/css/style.css
these styles should be added to:
assets/styles/app.scss

Webpack will then compile them for you.


When you added:
```
    <!-- CSS -->
    {{ encore_entry_link_tags('css/app') }}

    <link rel="stylesheet" href="{{asset('assets/css/style.css')}}">
    {% block stylesheets %}{% endblock %}

```
The line above is where the main style is being added: encore_entry_link_tags

yarn build / yarn dev server will build the css for you.

2023-05-16 02:07 UTC, illuminate3 requested changes

2023-05-16 02:07 UTC, illuminate3 commented on src/Controller/ProductController.php
CategoryRepository $cr,

Seeing $cr in the code, I don't know what it is right away and have to search for it. I know that javascript and java used to like sing character variables but they are not friendly for other developers and for yourself if you have to go back and fix the code. Please use full words on variables.

2023-05-16 02:07 UTC, illuminate3 commented on config/routes.yaml
Ah, I see. there are different ways to do this but it's normally better to go with what the project is doing.

2023-05-16 06:38 UTC, Devscaleupally commented on public/us-car-models-data-master/1992.csv
I merged the code from main to MN-8-left-column-sorting

2023-05-16 06:40 UTC, Devscaleupally commented on public/assets/css/style.css
okay thanks.

2023-05-17 06:14 UTC, illuminate3 requested changes
when you go into the subcategory view: acrua
products that have a category_ID = Parent_ID (acura) do not show.
Most likely my guess is that the code is only looking at models and not the make category id.

2023-05-17 13:17 UTC, Devscaleupally commented
Yes your guess is correct. So the logic is

1. Initially, there is no filter check; hence, all products are shown.

2. When the user selects a make, the backend checks for all the subcategories of the selected make and filters the products based on the subcategories (models). I assume that the product's category_id should be directly linked with the subcategory_id. Therefore, there is no need to check both the make and the model. A product cannot be linked only with a make; it should be linked with the combination of make and model.

Additionally, in the product table, Product 3 is directly linked with the main category_id and that's why it is not showing. This is my understanding, which is why I'm filtering the products only with models.

2023-05-18 01:42 UTC, closed without merging