Product management Cars API integration
illuminate3/minuet pull request #56
Opened 2023-06-02 14:51 UTC by miteshqodic

Product management Cars API integration

2023-06-03 02:52 UTC, illuminate3 requested changes

2023-06-03 02:52 UTC, illuminate3 commented on composer.json
Can you revert this change back to ^6.2

I don't know why I did it this way.

2023-06-03 02:52 UTC, illuminate3 commented on config/packages/framework.yaml
I noticed your curl implementation.
I'm wondering if you saw how I started doing it this way?

2023-06-03 02:52 UTC, illuminate3 commented on migrations/Version20230526051149.php
thanks for the work on the migrations!

I run the command from this file:
src/Command/DevCommand.php

bin/console app:dev

It will drop, create, migrate from the entities, and then run fixtures.

I don't plan to run migrations yet.

If the entities are correct, we can skip doing migrations.

I can't load the db with  this command and tried to load by hand. We are missing a slug column.

I have been using the make:entity command for my relations and Symfony will create the associations between the tables like product <-> product_trims.
We should keep the code consistent.

2023-06-03 02:52 UTC, illuminate3 commented on src/Controller/MainController.php
> +    public function index(
This was my original proof of concept.
If we aren't using it then we should remove the code.

Was there a reason why you didn't start from here?

2023-06-03 02:52 UTC, illuminate3 commented on src/Entity/Image.php
> +    // use CreatedAtTrait;
There is a trait here that can be used.

I commented and left it in the code in case we needed it.

Please compare against the trait and see if we can use it.
I like keeping the entities clean.

2023-06-03 02:52 UTC, illuminate3 commented on src/Entity/Product.php
I was thinking that a product_details entity would be a great place to move all the api information into that.

I am trying to think forward to when and or if we add or change to another API company.

2023-06-03 02:52 UTC, illuminate3 commented on src/Utils/GeneralUtil.php
> +        $data = array('api_token' => '9ecb27a8-c1dd-4630-9f70-6d1c0ade1235', 'api_secret' => '13592e0f2f841f45f7c0531fbbed1ff1');
The API shouldn't be hard coded.
I have assigned these env variables already.

2023-06-05 06:40 UTC, miteshqodic commented on src/Entity/Product.php
Ok we will create separate table to store the other product details (which is coming from api) in to the "product_details" table and basic details will be stored in product table like, id, account_id, title, category_id, description, price etc
Is this correct ?

2023-06-06 15:20 UTC, miteshqodic commented on src/Controller/MainController.php
> +    public function index(
We have implemented the cars api logic to products page, so that is why this is not needed in this controller

2023-06-07 03:16 UTC, merged