fixed make model filter bug
illuminate3/minuet pull request #58
Opened 2023-06-14 10:56 UTC by Devscaleupally

2023-06-15 03:45 UTC, illuminate3 requested changes
Still can not register

2023-06-15 03:45 UTC, illuminate3 commented on assets/js/common.js
Why is this file needed?

2023-06-15 03:45 UTC, illuminate3 commented on src/Controller/Auth/RegisterController.php
Why are you using a try and catch?
The symfony controllers normally don't use this.

2023-06-15 03:45 UTC, illuminate3 commented on webpack.config.js
if common.js is not needed. then it isn't needed here too

2023-06-15 03:45 UTC, illuminate3 commented on src/Controller/Auth/RegisterController.php
> +            if ($form->isSubmitted() && $form->isValid()) {
$from->isValid() = false
during my testing of the main branch and your code.

$form->getErrors() = null value needs to have data.
Stupid symfony ... won't say what value that is being based as null for validation.

The form has 3 inputs.
email, password, and agree to terms.

the form validation is failing because of null value.

I suspect it's a role issue. I can't think of anything else even after reviewing the User Table.

2023-06-16 00:56 UTC, illuminate3 requested changes
Has main branch been merged into this branch?

2023-06-17 05:28 UTC, Devscaleupally commented
Yes, main branch is merged in this branch.

2023-06-20 07:18 UTC, Devscaleupally commented
Yes main branch is merged in this branch.

2023-06-22 23:52 UTC, merged