MN-56-buyer-on-register-should-go-to-a-landing-page-24
illuminate3/minuet pull request #65
Opened 2023-06-17 05:35 UTC by Devscaleupally

2023-06-18 20:37 UTC, illuminate3 requested changes

2023-06-18 20:37 UTC, illuminate3 commented on assets/js/common.js
remove this

2023-06-18 20:37 UTC, illuminate3 commented on webpack.config.js
remove this

2023-06-18 20:37 UTC, illuminate3 commented on src/Controller/Auth/RegisterController.php
The Try catch block isn't needed most likely. Also I suspect it will change how the controller works at the moment.

Please confirm with the main branch again.

2023-06-20 06:53 UTC, Devscaleupally commented on assets/js/common.js
deleted this file and also remove it from webpack.config.js

2023-06-20 06:53 UTC, Devscaleupally commented on webpack.config.js
Why do you want to remove this file? This file is responsible to minify the js files while creating the build.

2023-06-20 06:54 UTC, Devscaleupally commented on src/Controller/Auth/RegisterController.php
Okay I will remove try catch block. And code is synced with the main branch.

2023-06-21 02:52 UTC, illuminate3 commented on webpack.config.js
the common.js isn't need in that file anymore

2023-06-21 03:10 UTC, illuminate3 approved these changes

2023-06-21 03:11 UTC, merged